title: t0ronto.ca
description: >- # this means to ignore newlines until "baseurl:"
  Toronto Digital Commons // Toronto Data Commons
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://t0ronto.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed

collections:
  communities:
    output: false
    # permalink: /:collection/:name/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
